var APT_STATUS;
(function (APT_STATUS) {
    APT_STATUS["PENDDING"] = "PENDDING";
    APT_STATUS["FULFILLED"] = "FULFILLED";
    APT_STATUS["REJECTTED"] = "REJECTTED"; //PROMISE
})(APT_STATUS || (APT_STATUS = {}));
var a1 = APT_STATUS.PENDDING;
var a2 = APT_STATUS.FULFILLED;
